import type { BusinessCard } from "./types";

export const sampleCards: BusinessCard[] = [
  {
    id: "sample-aether",
    company: "Aether Studio",
    personName: "Maya Chen",
    title: "Creative Director",
    phone: "415.555.0118",
    email: "maya@aether.studio",
    website: "aether.studio",
    address: "1201 Valencia Street, San Francisco CA 94110",
    notes: "Studio hours by appointment.",
    line: "Design",
    frontImage: "/cards/aether-front.jpg",
    backImage: "/cards/aether-back.jpg",
    createdAt: 1,
    isSample: true,
  },
  {
    id: "sample-brightwell",
    company: "Brightwell Law",
    personName: "James Brightwell",
    title: "Partner",
    phone: "212.555.0144",
    email: "james@brightwell.law",
    website: "brightwell.law",
    address: "One Wall Street, 28th Floor, New York NY 10005",
    notes: "Confidential. For the intended recipient only.",
    line: "Law",
    frontImage: "/cards/brightwell-front.jpg",
    backImage: "/cards/brightwell-back.jpg",
    createdAt: 2,
    isSample: true,
  },
  {
    id: "sample-cedar",
    company: "Cedar & Salt",
    personName: "Elena Rossi",
    title: "Chef & Owner",
    phone: "415.555.0172",
    email: "reservations@cedarandsalt.com",
    website: "cedarandsalt.com",
    address: "Pacific Heights, San Francisco",
    notes: "Dinner Wednesday through Sunday.",
    line: "Food",
    frontImage: "/cards/cedar-front.jpg",
    backImage: null,
    createdAt: 3,
    isSample: true,
  },
  {
    id: "sample-driftwood",
    company: "Driftwood Interiors",
    personName: "Tomas Hale",
    title: "Principal",
    phone: "212.555.0160",
    email: "tomas@driftwood.studio",
    website: "driftwood.studio",
    address: "14 Mercer Street, New York",
    notes: "Residential interiors and spatial direction.",
    line: "Interiors",
    frontImage: "/cards/driftwood-front.jpg",
    backImage: null,
    createdAt: 4,
    isSample: true,
  },
  {
    id: "sample-ember",
    company: "Ember & Oak Wines",
    personName: "Sophie Laurent",
    title: "Importer",
    phone: "707.555.0133",
    email: "sophie@emberandoak.com",
    website: "emberandoak.com",
    address: "Napa Valley, California",
    notes: "Small-grower wines from France and California.",
    line: "Wine",
    frontImage: "/cards/ember-front.jpg",
    backImage: null,
    createdAt: 5,
    isSample: true,
  },
  {
    id: "sample-fieldnotes",
    company: "Field Notes Photo",
    personName: "Alex Rivera",
    title: "Photographer",
    phone: "323.555.0188",
    email: "alex@fieldnotes.photo",
    website: "fieldnotes.photo",
    address: "Los Angeles, California",
    notes: "Editorial and portrait work.",
    line: "Photo",
    frontImage: "/cards/fieldnotes-front.jpg",
    backImage: null,
    createdAt: 6,
    isSample: true,
  },
  {
    id: "sample-grove",
    company: "Grove Botanica",
    personName: "Naomi Park",
    title: "Florist",
    phone: "415.555.0198",
    email: "hello@grovebotanica.com",
    website: "grovebotanica.com",
    address: "48 Filbert Street, San Francisco",
    notes: "Seasonal arrangements, weddings, and weekly studio visits.",
    line: "Flowers",
    frontImage: "/cards/grove-front.jpg",
    backImage: "/cards/grove-back.jpg",
    createdAt: 7,
    isSample: true,
  },
  {
    id: "sample-harbor",
    company: "Harbor Type",
    personName: "Lin Zhao",
    title: "Type Designer",
    phone: "503.555.0129",
    email: "lin@harbor.type",
    website: "harbor.type",
    address: "Portland, OR",
    notes: "Custom typefaces and lettering.",
    line: "Type",
    frontImage: "/cards/harbor-front.jpg",
    backImage: null,
    createdAt: 8,
    isSample: true,
  },
  {
    id: "sample-ironclad",
    company: "Ironclad Construction",
    personName: "Marcus Hale",
    title: "General Contractor",
    phone: "503.555.0140",
    email: "marcus@ironclad.build",
    website: "ironclad.build",
    address: "Portland, Oregon",
    notes: "Residential and light commercial builds.",
    line: "Construction",
    frontImage: "/cards/ironclad-front.jpg",
    backImage: null,
    createdAt: 9,
    isSample: true,
  },
  {
    id: "sample-juniper",
    company: "Juniper Fishing Co.",
    personName: "Rosa Juniper",
    title: "Captain",
    phone: "503.555.0177",
    email: "rosa@juniperfishing.com",
    website: "juniperfishing.com",
    address: "Astoria, Oregon",
    notes: "Charters on the Columbia and the coast.",
    line: "Fishing",
    frontImage: "/cards/juniper-front.jpg",
    backImage: null,
    createdAt: 10,
    isSample: true,
  },
  {
    id: "sample-kestrel",
    company: "Kestrel Glass",
    personName: "Ivy Kestrel",
    title: "Glassworker",
    phone: "503.555.0166",
    email: "ivy@kestrel.glass",
    website: "kestrel.glass",
    address: "Portland, Oregon",
    notes: "Architectural glass and one-off vessels.",
    line: "Glass",
    frontImage: "/cards/kestrel-front.jpg",
    backImage: null,
    createdAt: 11,
    isSample: true,
  },
];
